apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Chart.Name }}
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: hwchiu/cicd-app:{{ .Values.nginx.image.tag }}
        ports:
        - containerPort: 80
        imagePullPolicy: {{ .Values.nginx.pullPolicy }}
